# Label to use when marking an issue or PR as stale
staleLabel: stale

pulls:
  daysUntilStale: 30
  daysUntilClose: 14
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
issues:
  daysUntilStale: 30
  daysUntilClose: 14
  markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.
 exemptLabels:
   - bug
   - enhancement
   - feature
   - question
