name: 0x-rfq-api-pipeline-sha
kind: pipeline
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: publish-sha
    image: plugins/ecr
    settings:
      repo: 0x-rfq-api
      registry: 883408475785.dkr.ecr.us-east-1.amazonaws.com
      region: us-east-1
      tags:
        - ${DRONE_COMMIT_SHA}
        - commit-${DRONE_COMMIT_SHA}
trigger:
  event:
    exclude:
    - pull_request # To avoid building the image twice in a PR
node_selector:
  drone-builds: true
