version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=api
            - POSTGRES_PASSWORD=api
            - POSTGRES_DB=api
        # persist the postgres data to disk so we don't lose it
        # on rebuilds.
        ports:
            - '5432:5432'
    redis:
        image: redis:6.0
        ports:
            - '6379:6379'
