[profile.default]
src = 'src'
out = 'out'
libs = [
    'lib',
    'node_modules',
]
remappings = [
    '@0x/contracts-utils/=../utils/'
]
allow_paths = [
    '../utils/'
]

fs_permissions = [{ access = "read", path = "./out/ZRXToken.sol" }]

optimizer_runs = 1_000_000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
