apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: rfqm
    app.kubernetes.io/component: dummy-mm
  name: rfq-dummy-mm
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rfqm
      app.kubernetes.io/component: dummy-mm
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app.kubernetes.io/name: rfqm
        app.kubernetes.io/component: dummy-mm
    spec:
      containers:
        - image: 0x-rfq-api:latest
          name: rfq-dummy-mm
          resources:
            limits:
              cpu: 800m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          command: ["/bin/sh", "-c"]
          args: ["update-ca-certificates; yarn start:service:dummy_mm_http"]
          ports:
            - containerPort: 3001
              name: http
            - containerPort: 8080
              name: prom
          env:
            - name: NODE_ENV
              value: "production"
            - name: HTTP_PORT
              value: "3001"
            - name: LOGGER_INCLUDE_TIMESTAMP
              value: "false"
            - name: ETHEREUM_RPC_URL
              value: ""
            - name: CHAIN_ID
              value: "3"
            - name: ETH_GAS_STATION_API_URL
              value: ""
            - name: ENABLE_PROMETHEUS_METRICS
              value: "true"
            - name: PROMETHEUS_PORT
              value: "8080"
            - name: AWS_REGION
              value: "us-east-1"
