[default]
src = 'contracts/src'
out = 'foundry-artifacts'
libs = ['../utils/contracts/src/']
remappings = ['@0x/contracts-utils/=../utils/', '@0x/contracts-erc20/=../erc20/']
cache_path = 'foundry-cache'
optimizer_runs = 1000000