[profile.default]
src = 'contracts/src'
out = 'foundry-artifacts'
test = 'contracts/test/foundry'
libs = ["contracts/deps/", "../utils/contracts/src/"]
remappings = [
    '@0x/contracts-utils/=../utils/',
    '@0x/contracts-erc20/=../erc20/',
    'src/=./contracts/src',
    '@0x/contract-addresses/=../../packages/contract-addresses',
    '@0x/samplers/=contracts/src/samplers',
]
cache_path = 'foundry-cache'
optimizer_runs = 1000000
fs_permissions = [
    { access = "read-write", path = "./contracts/test/foundry/addresses" },
]
verbosity = 3
#these rpc's are publicly available on rpc.info not internal rpcs
[rpc_endpoints]
arbitrum = "https://rpc.ankr.com/arbitrum"
avalanche = "https://api.avax.network/ext/bc/C/rpc"
bsc = "https://bsc-dataseed1.binance.org/"
fantom = "https://rpc.ftm.tools/"
mainnet = "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
optimism = "https://mainnet.optimism.io"
polygon = "https://polygon-rpc.com"
