[profile.default]
src = 'contracts/src'
out = 'foundry-artifacts'
test = 'tests'
libs = ["contracts/deps/", "../utils/contracts/src/"]
remappings = ['@0x/contracts-utils/=../utils/', '@0x/contracts-erc20/=../erc20/', 'src/=./contracts/src']
optimizer_runs = 1000000

