[profile.default]
src = 'contracts/src'
out = 'foundry-artifacts'
test = 'contracts/test/foundry/local'
libs = ["contracts/deps/", "../utils/contracts/src/"]
remappings = [
    'forge-std/=contracts/deps/forge-std/src/',
    'ds-test/=contracts/deps/forge-std/lib/ds-test/src/',
    '@0x/contracts-utils/=../utils/',
    '@0x/contracts-erc20/=../erc20/',
    'src/=./contracts/src',
    '@0x/contract-addresses/=../../packages/contract-addresses',
    'samplers/=contracts/test/samplers',
]
optimizer_runs = 1000000
fs_permissions = [
    { access = "read-write", path = "./contracts/test/foundry/addresses" },
]
verbosity = 3

[profile.local]
test = 'contracts/test/foundry/local'
[profile.forked]
test = 'contracts/test/foundry/forked'

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
bsc = "${BSC_RPC_URL}"
fantom = "${FANTOM_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
