[profile.default]
src = 'contracts/src'
out = 'foundry-artifacts'
test = 'contracts/test/foundry'
libs = ["contracts/deps/", "../utils/contracts/src/"]
remappings = [
    '@0x/contracts-utils/=../utils/',
    '@0x/contracts-erc20/=../erc20/',
    'src/=./contracts/src',
    '@0x/contract-addresses/=../../packages/contract-addresses',
    '@0x/samplers/=contracts/src/samplers',
]
cache_path = 'foundry-cache'
optimizer_runs = 1000000
fs_permissions = [
    { access = "read-write", path = "./contracts/test/foundry/addresses" },
]
verbosity = 3
rpc_endpoints = { arbitrum = "${FORGE_ARBITRUM_RPC}", avalanche = "${FORGE_AVALANCHE_RPC}", bsc = "${FORGE_BSC_RPC}", fantom = "${FORGE_FANTOM_RPC}", mainnet = "${FORGE_MAINNET_RPC}", optimism = "${FORGE_OPTIMISM_RPC}", polygon = "${FORGE_POLYGON_RPC}" }
