name: Docker

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_REGISTRY_URL: 883408475785.dkr.ecr.us-east-1.amazonaws.com/0x-rfq-api

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::883408475785:role/github-actions
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
         push: true
         tags: ${{ env.DOCKER_REGISTRY_URL }}:${{ github.sha }}
      - name: Comment PR the Docker Image for the PR
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            A Docker image has been built for this PR, please use this image if you want to deploy changes on this PR somewhere:
            ```
            ${{ env.DOCKER_REGISTRY_URL }}:${{ github.sha }}
            ```
          GITHUB_TOKEN: ${{ secrets.PAT }}
