/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as IOwnable from '../generated-artifacts/IOwnable.json';
import * as LibBytes from '../generated-artifacts/LibBytes.json';
import * as LibBytesRichErrors from '../generated-artifacts/LibBytesRichErrors.json';
import * as LibOwnableRichErrors from '../generated-artifacts/LibOwnableRichErrors.json';
import * as LibReentrancyGuardRichErrors from '../generated-artifacts/LibReentrancyGuardRichErrors.json';
import * as LibRichErrors from '../generated-artifacts/LibRichErrors.json';
import * as LibSafeMath from '../generated-artifacts/LibSafeMath.json';
import * as LibSafeMathRichErrors from '../generated-artifacts/LibSafeMathRichErrors.json';
import * as Ownable from '../generated-artifacts/Ownable.json';
import * as ReentrancyGuard from '../generated-artifacts/ReentrancyGuard.json';
export const artifacts = {
    IOwnable: IOwnable as ContractArtifact,
    LibBytes: LibBytes as ContractArtifact,
    LibBytesRichErrors: LibBytesRichErrors as ContractArtifact,
    LibOwnableRichErrors: LibOwnableRichErrors as ContractArtifact,
    LibReentrancyGuardRichErrors: LibReentrancyGuardRichErrors as ContractArtifact,
    LibRichErrors: LibRichErrors as ContractArtifact,
    LibSafeMath: LibSafeMath as ContractArtifact,
    LibSafeMathRichErrors: LibSafeMathRichErrors as ContractArtifact,
    Ownable: Ownable as ContractArtifact,
    ReentrancyGuard: ReentrancyGuard as ContractArtifact,
};
