[profile.default]
src = 'src'
out = 'foundry-artifacts'
test = 'test'
path_pattern = '*.t.sol'
libs = ["lib"]
remappings = [
    '@0x/contracts-utils/=../node_modules/@0x/contracts-utils/',
    '@0x/contracts-erc20/=../node_modules/@0x/contracts-erc20/',
    '@0x/contracts-zero-ex/=../node_modules/@0x/contracts-zero-ex/',
    '@uniswap/v3-core/=../node_modules/@uniswap/v3-core/',
    '@uniswap/v3-periphery/=../node_modules/@uniswap/v3-periphery/',
    '@kyberelastic/=../node_modules/@kybernetwork/ks-elastic-sc/contracts/',
    '@cryptoalgebra/core/=../node_modules/@cryptoalgebra/core/',
    '@cryptoalgebra/periphery/=../node_modules/@cryptoalgebra/periphery/'
]
allow_paths = ["../node_modules"]
cache_path = 'foundry-cache'
optimizer_runs = 1000000
fs_permissions = [{ access = "read-write", path = "./"}]