[profile.default]
src = 'src'
out = 'out'
libs = ['lib', "../utils/contracts/src/"]
fs_permissions = [{ access = "read", path = "./" }]
remappings = [
    '@openzeppelin/=./lib/openzeppelin-contracts/contracts/',
    '@openzeppelin-contracts-upgradeable/=./lib/openzeppelin-contracts-upgradeable/contracts/',
    '@0x/contracts-utils/=../utils/',
]
solc = '0.8.19'
optimizer_runs = 20_000
via_ir = true

[profile.smt.model_checker]
engine = 'chc'
timeout = 10_000
targets = [
    'assert',
    'constantCondition',
    'divByZero',
    'outOfBounds',
    'underflow'
]
contracts = { 'src/ZeroExProtocolGovernor.sol' = [ 'ZeroExProtocolGovernor' ] }
