[profile.default]
src = 'src'
out = 'out'
libs = ['lib', "../utils/contracts/src/"]
fs_permissions = [{ access = "read", path = "./" }]
remappings = [
    '@openzeppelin/=./lib/openzeppelin-contracts/contracts/',
    '@0x/contracts-utils/=../utils/',
]
optimizer_runs = 20_000
