/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as BalanceChecker from '../test/generated-artifacts/BalanceChecker.json';
import * as BalancerSampler from '../test/generated-artifacts/BalancerSampler.json';
import * as BalancerV2Sampler from '../test/generated-artifacts/BalancerV2Sampler.json';
import * as BancorSampler from '../test/generated-artifacts/BancorSampler.json';
import * as BoosterSampler from '../test/generated-artifacts/BoosterSampler.json';
import * as CurveSampler from '../test/generated-artifacts/CurveSampler.json';
import * as CurveV2Sampler from '../test/generated-artifacts/CurveV2Sampler.json';
import * as DelegateHackedERC20 from '../test/generated-artifacts/DelegateHackedERC20.json';
import * as DODOSampler from '../test/generated-artifacts/DODOSampler.json';
import * as DODOV2Sampler from '../test/generated-artifacts/DODOV2Sampler.json';
import * as DummyLiquidityProvider from '../test/generated-artifacts/DummyLiquidityProvider.json';
import * as ERC20BridgeSampler from '../test/generated-artifacts/ERC20BridgeSampler.json';
import * as Eth2DaiSampler from '../test/generated-artifacts/Eth2DaiSampler.json';
import * as FakeTaker from '../test/generated-artifacts/FakeTaker.json';
import * as GasOverhead from '../test/generated-artifacts/GasOverhead.json';
import * as HackedERC20 from '../test/generated-artifacts/HackedERC20.json';
import * as IEth2Dai from '../test/generated-artifacts/IEth2Dai.json';
import * as IKyberNetwork from '../test/generated-artifacts/IKyberNetwork.json';
import * as IUniswapExchangeQuotes from '../test/generated-artifacts/IUniswapExchangeQuotes.json';
import * as IUniswapV2Router01 from '../test/generated-artifacts/IUniswapV2Router01.json';
import * as KyberDmmSampler from '../test/generated-artifacts/KyberDmmSampler.json';
import * as KyberSampler from '../test/generated-artifacts/KyberSampler.json';
import * as LidoSampler from '../test/generated-artifacts/LidoSampler.json';
import * as LiquidityProviderSampler from '../test/generated-artifacts/LiquidityProviderSampler.json';
import * as MakerPSMSampler from '../test/generated-artifacts/MakerPSMSampler.json';
import * as MooniswapSampler from '../test/generated-artifacts/MooniswapSampler.json';
import * as MStableSampler from '../test/generated-artifacts/MStableSampler.json';
import * as NativeOrderSampler from '../test/generated-artifacts/NativeOrderSampler.json';
import * as ShellSampler from '../test/generated-artifacts/ShellSampler.json';
import * as SwapRevertSampler from '../test/generated-artifacts/SwapRevertSampler.json';
import * as TestERC20BridgeSampler from '../test/generated-artifacts/TestERC20BridgeSampler.json';
import * as TestNativeOrderSampler from '../test/generated-artifacts/TestNativeOrderSampler.json';
import * as TwoHopSampler from '../test/generated-artifacts/TwoHopSampler.json';
import * as UniswapSampler from '../test/generated-artifacts/UniswapSampler.json';
import * as UniswapV2Sampler from '../test/generated-artifacts/UniswapV2Sampler.json';
import * as UniswapV3Sampler from '../test/generated-artifacts/UniswapV3Sampler.json';
import * as UtilitySampler from '../test/generated-artifacts/UtilitySampler.json';
export const artifacts = {
    BalanceChecker: BalanceChecker as ContractArtifact,
    BalancerSampler: BalancerSampler as ContractArtifact,
    BalancerV2Sampler: BalancerV2Sampler as ContractArtifact,
    BancorSampler: BancorSampler as ContractArtifact,
    BoosterSampler: BoosterSampler as ContractArtifact,
    CurveSampler: CurveSampler as ContractArtifact,
    CurveV2Sampler: CurveV2Sampler as ContractArtifact,
    DODOSampler: DODOSampler as ContractArtifact,
    DODOV2Sampler: DODOV2Sampler as ContractArtifact,
    DelegateHackedERC20: DelegateHackedERC20 as ContractArtifact,
    ERC20BridgeSampler: ERC20BridgeSampler as ContractArtifact,
    Eth2DaiSampler: Eth2DaiSampler as ContractArtifact,
    FakeTaker: FakeTaker as ContractArtifact,
    GasOverhead: GasOverhead as ContractArtifact,
    HackedERC20: HackedERC20 as ContractArtifact,
    KyberDmmSampler: KyberDmmSampler as ContractArtifact,
    KyberSampler: KyberSampler as ContractArtifact,
    LidoSampler: LidoSampler as ContractArtifact,
    LiquidityProviderSampler: LiquidityProviderSampler as ContractArtifact,
    MStableSampler: MStableSampler as ContractArtifact,
    MakerPSMSampler: MakerPSMSampler as ContractArtifact,
    MooniswapSampler: MooniswapSampler as ContractArtifact,
    NativeOrderSampler: NativeOrderSampler as ContractArtifact,
    ShellSampler: ShellSampler as ContractArtifact,
    SwapRevertSampler: SwapRevertSampler as ContractArtifact,
    TwoHopSampler: TwoHopSampler as ContractArtifact,
    UniswapSampler: UniswapSampler as ContractArtifact,
    UniswapV2Sampler: UniswapV2Sampler as ContractArtifact,
    UniswapV3Sampler: UniswapV3Sampler as ContractArtifact,
    UtilitySampler: UtilitySampler as ContractArtifact,
    IEth2Dai: IEth2Dai as ContractArtifact,
    IKyberNetwork: IKyberNetwork as ContractArtifact,
    IUniswapExchangeQuotes: IUniswapExchangeQuotes as ContractArtifact,
    IUniswapV2Router01: IUniswapV2Router01 as ContractArtifact,
    DummyLiquidityProvider: DummyLiquidityProvider as ContractArtifact,
    TestERC20BridgeSampler: TestERC20BridgeSampler as ContractArtifact,
    TestNativeOrderSampler: TestNativeOrderSampler as ContractArtifact,
};
