/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as ApproximateBuys from '../test/generated-artifacts/ApproximateBuys.json';
import * as BalanceChecker from '../test/generated-artifacts/BalanceChecker.json';
import * as BalancerSampler from '../test/generated-artifacts/BalancerSampler.json';
import * as BalancerV2Sampler from '../test/generated-artifacts/BalancerV2Sampler.json';
import * as BancorSampler from '../test/generated-artifacts/BancorSampler.json';
import * as CompoundSampler from '../test/generated-artifacts/CompoundSampler.json';
import * as CurveSampler from '../test/generated-artifacts/CurveSampler.json';
import * as DODOSampler from '../test/generated-artifacts/DODOSampler.json';
import * as DODOV2Sampler from '../test/generated-artifacts/DODOV2Sampler.json';
import * as DummyLiquidityProvider from '../test/generated-artifacts/DummyLiquidityProvider.json';
import * as ERC20BridgeSampler from '../test/generated-artifacts/ERC20BridgeSampler.json';
import * as FakeTaker from '../test/generated-artifacts/FakeTaker.json';
import * as IBalancer from '../test/generated-artifacts/IBalancer.json';
import * as IBancor from '../test/generated-artifacts/IBancor.json';
import * as ICurve from '../test/generated-artifacts/ICurve.json';
import * as IKyberNetwork from '../test/generated-artifacts/IKyberNetwork.json';
import * as IMooniswap from '../test/generated-artifacts/IMooniswap.json';
import * as IMStable from '../test/generated-artifacts/IMStable.json';
import * as IMultiBridge from '../test/generated-artifacts/IMultiBridge.json';
import * as IShell from '../test/generated-artifacts/IShell.json';
import * as ISmoothy from '../test/generated-artifacts/ISmoothy.json';
import * as IUniswapExchangeQuotes from '../test/generated-artifacts/IUniswapExchangeQuotes.json';
import * as IUniswapV2Router01 from '../test/generated-artifacts/IUniswapV2Router01.json';
import * as KyberDmmSampler from '../test/generated-artifacts/KyberDmmSampler.json';
import * as KyberSampler from '../test/generated-artifacts/KyberSampler.json';
import * as LidoSampler from '../test/generated-artifacts/LidoSampler.json';
import * as LiquidityProviderSampler from '../test/generated-artifacts/LiquidityProviderSampler.json';
import * as MakerPSMSampler from '../test/generated-artifacts/MakerPSMSampler.json';
import * as MooniswapSampler from '../test/generated-artifacts/MooniswapSampler.json';
import * as MStableSampler from '../test/generated-artifacts/MStableSampler.json';
import * as MultiBridgeSampler from '../test/generated-artifacts/MultiBridgeSampler.json';
import * as NativeOrderSampler from '../test/generated-artifacts/NativeOrderSampler.json';
import * as SamplerUtils from '../test/generated-artifacts/SamplerUtils.json';
import * as ShellSampler from '../test/generated-artifacts/ShellSampler.json';
import * as SmoothySampler from '../test/generated-artifacts/SmoothySampler.json';
import * as TestERC20BridgeSampler from '../test/generated-artifacts/TestERC20BridgeSampler.json';
import * as TestNativeOrderSampler from '../test/generated-artifacts/TestNativeOrderSampler.json';
import * as TwoHopSampler from '../test/generated-artifacts/TwoHopSampler.json';
import * as UniswapSampler from '../test/generated-artifacts/UniswapSampler.json';
import * as UniswapV2Sampler from '../test/generated-artifacts/UniswapV2Sampler.json';
import * as UniswapV3Sampler from '../test/generated-artifacts/UniswapV3Sampler.json';
import * as UtilitySampler from '../test/generated-artifacts/UtilitySampler.json';
export const artifacts = {
    ApproximateBuys: ApproximateBuys as ContractArtifact,
    BalanceChecker: BalanceChecker as ContractArtifact,
    BalancerSampler: BalancerSampler as ContractArtifact,
    BalancerV2Sampler: BalancerV2Sampler as ContractArtifact,
    BancorSampler: BancorSampler as ContractArtifact,
    CompoundSampler: CompoundSampler as ContractArtifact,
    CurveSampler: CurveSampler as ContractArtifact,
    DODOSampler: DODOSampler as ContractArtifact,
    DODOV2Sampler: DODOV2Sampler as ContractArtifact,
    ERC20BridgeSampler: ERC20BridgeSampler as ContractArtifact,
    FakeTaker: FakeTaker as ContractArtifact,
    KyberDmmSampler: KyberDmmSampler as ContractArtifact,
    KyberSampler: KyberSampler as ContractArtifact,
    LidoSampler: LidoSampler as ContractArtifact,
    LiquidityProviderSampler: LiquidityProviderSampler as ContractArtifact,
    MStableSampler: MStableSampler as ContractArtifact,
    MakerPSMSampler: MakerPSMSampler as ContractArtifact,
    MooniswapSampler: MooniswapSampler as ContractArtifact,
    MultiBridgeSampler: MultiBridgeSampler as ContractArtifact,
    NativeOrderSampler: NativeOrderSampler as ContractArtifact,
    SamplerUtils: SamplerUtils as ContractArtifact,
    ShellSampler: ShellSampler as ContractArtifact,
    SmoothySampler: SmoothySampler as ContractArtifact,
    TwoHopSampler: TwoHopSampler as ContractArtifact,
    UniswapSampler: UniswapSampler as ContractArtifact,
    UniswapV2Sampler: UniswapV2Sampler as ContractArtifact,
    UniswapV3Sampler: UniswapV3Sampler as ContractArtifact,
    UtilitySampler: UtilitySampler as ContractArtifact,
    IBalancer: IBalancer as ContractArtifact,
    IBancor: IBancor as ContractArtifact,
    ICurve: ICurve as ContractArtifact,
    IKyberNetwork: IKyberNetwork as ContractArtifact,
    IMStable: IMStable as ContractArtifact,
    IMooniswap: IMooniswap as ContractArtifact,
    IMultiBridge: IMultiBridge as ContractArtifact,
    IShell: IShell as ContractArtifact,
    ISmoothy: ISmoothy as ContractArtifact,
    IUniswapExchangeQuotes: IUniswapExchangeQuotes as ContractArtifact,
    IUniswapV2Router01: IUniswapV2Router01 as ContractArtifact,
    DummyLiquidityProvider: DummyLiquidityProvider as ContractArtifact,
    TestERC20BridgeSampler: TestERC20BridgeSampler as ContractArtifact,
    TestNativeOrderSampler: TestNativeOrderSampler as ContractArtifact,
};
