/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
export * from '../test/generated-wrappers/balance_checker';
export * from '../test/generated-wrappers/fake_taker';
