apiVersion: v1
kind: Service
metadata:
  name: gasless-swap-api
  labels:
    app.kubernetes.io/name: gasless-swap
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gasless-swap
    app.kubernetes.io/component: api
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
