/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as ERC20BridgeSampler from '../generated-artifacts/ERC20BridgeSampler.json';
export const artifacts = { ERC20BridgeSampler: ERC20BridgeSampler as ContractArtifact };
