/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as ApproximateBuys from '../generated-artifacts/ApproximateBuys.json';
import * as BalanceChecker from '../generated-artifacts/BalanceChecker.json';
import * as BalancerSampler from '../generated-artifacts/BalancerSampler.json';
import * as BalancerV2BatchSampler from '../generated-artifacts/BalancerV2BatchSampler.json';
import * as BalancerV2Common from '../generated-artifacts/BalancerV2Common.json';
import * as BalancerV2Sampler from '../generated-artifacts/BalancerV2Sampler.json';
import * as BancorSampler from '../generated-artifacts/BancorSampler.json';
import * as BancorV3Sampler from '../generated-artifacts/BancorV3Sampler.json';
import * as CompoundSampler from '../generated-artifacts/CompoundSampler.json';
import * as CurveSampler from '../generated-artifacts/CurveSampler.json';
import * as DODOSampler from '../generated-artifacts/DODOSampler.json';
import * as DODOV2Sampler from '../generated-artifacts/DODOV2Sampler.json';
import * as ERC20BridgeSampler from '../generated-artifacts/ERC20BridgeSampler.json';
import * as FakeTaker from '../generated-artifacts/FakeTaker.json';
import * as GMXSampler from '../generated-artifacts/GMXSampler.json';
import * as IBalancer from '../generated-artifacts/IBalancer.json';
import * as IBalancerV2Vault from '../generated-artifacts/IBalancerV2Vault.json';
import * as IBancor from '../generated-artifacts/IBancor.json';
import * as IBancorV3 from '../generated-artifacts/IBancorV3.json';
import * as ICurve from '../generated-artifacts/ICurve.json';
import * as IGMX from '../generated-artifacts/IGMX.json';
import * as IMooniswap from '../generated-artifacts/IMooniswap.json';
import * as IMStable from '../generated-artifacts/IMStable.json';
import * as IMultiBridge from '../generated-artifacts/IMultiBridge.json';
import * as IPlatypus from '../generated-artifacts/IPlatypus.json';
import * as IShell from '../generated-artifacts/IShell.json';
import * as IUniswapExchangeQuotes from '../generated-artifacts/IUniswapExchangeQuotes.json';
import * as IUniswapV2Router01 from '../generated-artifacts/IUniswapV2Router01.json';
import * as KyberDmmSampler from '../generated-artifacts/KyberDmmSampler.json';
import * as LidoSampler from '../generated-artifacts/LidoSampler.json';
import * as LiquidityProviderSampler from '../generated-artifacts/LiquidityProviderSampler.json';
import * as MakerPSMSampler from '../generated-artifacts/MakerPSMSampler.json';
import * as MooniswapSampler from '../generated-artifacts/MooniswapSampler.json';
import * as MStableSampler from '../generated-artifacts/MStableSampler.json';
import * as NativeOrderSampler from '../generated-artifacts/NativeOrderSampler.json';
import * as PlatypusSampler from '../generated-artifacts/PlatypusSampler.json';
import * as SamplerUtils from '../generated-artifacts/SamplerUtils.json';
import * as ShellSampler from '../generated-artifacts/ShellSampler.json';
import * as SynthetixSampler from '../generated-artifacts/SynthetixSampler.json';
import * as TestNativeOrderSampler from '../generated-artifacts/TestNativeOrderSampler.json';
import * as TwoHopSampler from '../generated-artifacts/TwoHopSampler.json';
import * as UniswapSampler from '../generated-artifacts/UniswapSampler.json';
import * as UniswapV2Sampler from '../generated-artifacts/UniswapV2Sampler.json';
import * as UniswapV3Sampler from '../generated-artifacts/UniswapV3Sampler.json';
import * as UtilitySampler from '../generated-artifacts/UtilitySampler.json';
import * as VelodromeSampler from '../generated-artifacts/VelodromeSampler.json';
import * as WooPPSampler from '../generated-artifacts/WooPPSampler.json';
export const artifacts = {
    ApproximateBuys: ApproximateBuys as ContractArtifact,
    BalanceChecker: BalanceChecker as ContractArtifact,
    BalancerSampler: BalancerSampler as ContractArtifact,
    BalancerV2BatchSampler: BalancerV2BatchSampler as ContractArtifact,
    BalancerV2Common: BalancerV2Common as ContractArtifact,
    BalancerV2Sampler: BalancerV2Sampler as ContractArtifact,
    BancorSampler: BancorSampler as ContractArtifact,
    BancorV3Sampler: BancorV3Sampler as ContractArtifact,
    CompoundSampler: CompoundSampler as ContractArtifact,
    CurveSampler: CurveSampler as ContractArtifact,
    DODOSampler: DODOSampler as ContractArtifact,
    DODOV2Sampler: DODOV2Sampler as ContractArtifact,
    ERC20BridgeSampler: ERC20BridgeSampler as ContractArtifact,
    FakeTaker: FakeTaker as ContractArtifact,
    GMXSampler: GMXSampler as ContractArtifact,
    KyberDmmSampler: KyberDmmSampler as ContractArtifact,
    LidoSampler: LidoSampler as ContractArtifact,
    LiquidityProviderSampler: LiquidityProviderSampler as ContractArtifact,
    MStableSampler: MStableSampler as ContractArtifact,
    MakerPSMSampler: MakerPSMSampler as ContractArtifact,
    MooniswapSampler: MooniswapSampler as ContractArtifact,
    NativeOrderSampler: NativeOrderSampler as ContractArtifact,
    PlatypusSampler: PlatypusSampler as ContractArtifact,
    SamplerUtils: SamplerUtils as ContractArtifact,
    ShellSampler: ShellSampler as ContractArtifact,
    SynthetixSampler: SynthetixSampler as ContractArtifact,
    TwoHopSampler: TwoHopSampler as ContractArtifact,
    UniswapSampler: UniswapSampler as ContractArtifact,
    UniswapV2Sampler: UniswapV2Sampler as ContractArtifact,
    UniswapV3Sampler: UniswapV3Sampler as ContractArtifact,
    UtilitySampler: UtilitySampler as ContractArtifact,
    VelodromeSampler: VelodromeSampler as ContractArtifact,
    WooPPSampler: WooPPSampler as ContractArtifact,
    IBalancer: IBalancer as ContractArtifact,
    IBalancerV2Vault: IBalancerV2Vault as ContractArtifact,
    IBancor: IBancor as ContractArtifact,
    IBancorV3: IBancorV3 as ContractArtifact,
    ICurve: ICurve as ContractArtifact,
    IGMX: IGMX as ContractArtifact,
    IMStable: IMStable as ContractArtifact,
    IMooniswap: IMooniswap as ContractArtifact,
    IMultiBridge: IMultiBridge as ContractArtifact,
    IPlatypus: IPlatypus as ContractArtifact,
    IShell: IShell as ContractArtifact,
    IUniswapExchangeQuotes: IUniswapExchangeQuotes as ContractArtifact,
    IUniswapV2Router01: IUniswapV2Router01 as ContractArtifact,
    TestNativeOrderSampler: TestNativeOrderSampler as ContractArtifact,
};
