/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as AaveV2Sampler from '../test/generated-artifacts/AaveV2Sampler.json';
import * as AaveV3Sampler from '../test/generated-artifacts/AaveV3Sampler.json';
import * as ApproximateBuys from '../test/generated-artifacts/ApproximateBuys.json';
import * as BalanceChecker from '../test/generated-artifacts/BalanceChecker.json';
import * as BalancerSampler from '../test/generated-artifacts/BalancerSampler.json';
import * as BalancerV2BatchSampler from '../test/generated-artifacts/BalancerV2BatchSampler.json';
import * as BalancerV2Common from '../test/generated-artifacts/BalancerV2Common.json';
import * as BalancerV2Sampler from '../test/generated-artifacts/BalancerV2Sampler.json';
import * as BancorSampler from '../test/generated-artifacts/BancorSampler.json';
import * as BancorV3Sampler from '../test/generated-artifacts/BancorV3Sampler.json';
import * as CompoundSampler from '../test/generated-artifacts/CompoundSampler.json';
import * as CurveSampler from '../test/generated-artifacts/CurveSampler.json';
import * as DODOSampler from '../test/generated-artifacts/DODOSampler.json';
import * as DODOV2Sampler from '../test/generated-artifacts/DODOV2Sampler.json';
import * as ERC20BridgeSampler from '../test/generated-artifacts/ERC20BridgeSampler.json';
import * as FakeTaker from '../test/generated-artifacts/FakeTaker.json';
import * as GMXSampler from '../test/generated-artifacts/GMXSampler.json';
import * as IBalancer from '../test/generated-artifacts/IBalancer.json';
import * as IBalancerV2Vault from '../test/generated-artifacts/IBalancerV2Vault.json';
import * as IBancor from '../test/generated-artifacts/IBancor.json';
import * as IBancorV3 from '../test/generated-artifacts/IBancorV3.json';
import * as ICurve from '../test/generated-artifacts/ICurve.json';
import * as IGMX from '../test/generated-artifacts/IGMX.json';
import * as IMooniswap from '../test/generated-artifacts/IMooniswap.json';
import * as IMStable from '../test/generated-artifacts/IMStable.json';
import * as IPlatypus from '../test/generated-artifacts/IPlatypus.json';
import * as IShell from '../test/generated-artifacts/IShell.json';
import * as IUniswapExchangeQuotes from '../test/generated-artifacts/IUniswapExchangeQuotes.json';
import * as IUniswapV2Router01 from '../test/generated-artifacts/IUniswapV2Router01.json';
import * as KyberDmmSampler from '../test/generated-artifacts/KyberDmmSampler.json';
import * as LidoSampler from '../test/generated-artifacts/LidoSampler.json';
import * as MakerPSMSampler from '../test/generated-artifacts/MakerPSMSampler.json';
import * as MooniswapSampler from '../test/generated-artifacts/MooniswapSampler.json';
import * as MStableSampler from '../test/generated-artifacts/MStableSampler.json';
import * as NativeOrderSampler from '../test/generated-artifacts/NativeOrderSampler.json';
import * as PlatypusSampler from '../test/generated-artifacts/PlatypusSampler.json';
import * as SamplerUtils from '../test/generated-artifacts/SamplerUtils.json';
import * as ShellSampler from '../test/generated-artifacts/ShellSampler.json';
import * as SynthetixSampler from '../test/generated-artifacts/SynthetixSampler.json';
import * as TestNativeOrderSampler from '../test/generated-artifacts/TestNativeOrderSampler.json';
import * as TwoHopSampler from '../test/generated-artifacts/TwoHopSampler.json';
import * as UniswapSampler from '../test/generated-artifacts/UniswapSampler.json';
import * as UniswapV2Sampler from '../test/generated-artifacts/UniswapV2Sampler.json';
import * as UniswapV3MultiQuoter from '../test/generated-artifacts/UniswapV3MultiQuoter.json';
import * as UniswapV3Sampler from '../test/generated-artifacts/UniswapV3Sampler.json';
import * as UtilitySampler from '../test/generated-artifacts/UtilitySampler.json';
import * as VelodromeSampler from '../test/generated-artifacts/VelodromeSampler.json';
import * as WooPPSampler from '../test/generated-artifacts/WooPPSampler.json';
export const artifacts = {
    AaveV2Sampler: AaveV2Sampler as ContractArtifact,
    AaveV3Sampler: AaveV3Sampler as ContractArtifact,
    ApproximateBuys: ApproximateBuys as ContractArtifact,
    BalanceChecker: BalanceChecker as ContractArtifact,
    BalancerSampler: BalancerSampler as ContractArtifact,
    BalancerV2BatchSampler: BalancerV2BatchSampler as ContractArtifact,
    BalancerV2Common: BalancerV2Common as ContractArtifact,
    BalancerV2Sampler: BalancerV2Sampler as ContractArtifact,
    BancorSampler: BancorSampler as ContractArtifact,
    BancorV3Sampler: BancorV3Sampler as ContractArtifact,
    CompoundSampler: CompoundSampler as ContractArtifact,
    CurveSampler: CurveSampler as ContractArtifact,
    DODOSampler: DODOSampler as ContractArtifact,
    DODOV2Sampler: DODOV2Sampler as ContractArtifact,
    ERC20BridgeSampler: ERC20BridgeSampler as ContractArtifact,
    FakeTaker: FakeTaker as ContractArtifact,
    GMXSampler: GMXSampler as ContractArtifact,
    KyberDmmSampler: KyberDmmSampler as ContractArtifact,
    LidoSampler: LidoSampler as ContractArtifact,
    MStableSampler: MStableSampler as ContractArtifact,
    MakerPSMSampler: MakerPSMSampler as ContractArtifact,
    MooniswapSampler: MooniswapSampler as ContractArtifact,
    NativeOrderSampler: NativeOrderSampler as ContractArtifact,
    PlatypusSampler: PlatypusSampler as ContractArtifact,
    SamplerUtils: SamplerUtils as ContractArtifact,
    ShellSampler: ShellSampler as ContractArtifact,
    SynthetixSampler: SynthetixSampler as ContractArtifact,
    TwoHopSampler: TwoHopSampler as ContractArtifact,
    UniswapSampler: UniswapSampler as ContractArtifact,
    UniswapV2Sampler: UniswapV2Sampler as ContractArtifact,
    UniswapV3MultiQuoter: UniswapV3MultiQuoter as ContractArtifact,
    UniswapV3Sampler: UniswapV3Sampler as ContractArtifact,
    UtilitySampler: UtilitySampler as ContractArtifact,
    VelodromeSampler: VelodromeSampler as ContractArtifact,
    WooPPSampler: WooPPSampler as ContractArtifact,
    IBalancer: IBalancer as ContractArtifact,
    IBalancerV2Vault: IBalancerV2Vault as ContractArtifact,
    IBancor: IBancor as ContractArtifact,
    IBancorV3: IBancorV3 as ContractArtifact,
    ICurve: ICurve as ContractArtifact,
    IGMX: IGMX as ContractArtifact,
    IMStable: IMStable as ContractArtifact,
    IMooniswap: IMooniswap as ContractArtifact,
    IPlatypus: IPlatypus as ContractArtifact,
    IShell: IShell as ContractArtifact,
    IUniswapExchangeQuotes: IUniswapExchangeQuotes as ContractArtifact,
    IUniswapV2Router01: IUniswapV2Router01 as ContractArtifact,
    TestNativeOrderSampler: TestNativeOrderSampler as ContractArtifact,
};
