# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on: [push]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - run: yarn install --frozen-lockfile
    - run: yarn build
    # Pull the docker images so that they don't need to be pulled in the tests.

    - run: yarn build:proto
    - run: git diff --exit-code # Make CI fail if there are any file changes from proto build

    - run: docker-compose pull
    - run: yarn lint
    - run: yarn test
    - name: Save build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: lib
        path: lib
