name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build solution
        run: yarn build

      - name: Lint typescript
        run: yarn lint:ts

      - name: Lint solidity
        run: yarn lint:contracts

      - name: Run prettier
        run: yarn prettier:ci

      - name: Test @0x/contracts-*
        run: |
              yarn wsrun \
                -p @0x/contracts-multisig \
                -p @0x/contracts-utils \
                -p @0x/contracts-exchange-libs \
                -p @0x/contracts-erc20 \
                -p @0x/contracts-erc721 \
                -p @0x/contracts-erc1155 \
                -p @0x/contracts-asset-proxy \
                -p @0x/contracts-broker \
                -p @0x/contracts-zero-ex \
                -m --serial -c test:circleci
